### ISSUE TITLE
Question pom scm/tag conflict

### ISSUE THREAD

**Issue by TomJahncke** [ralfth/pom-merge-driver#5]
The pom-merge-driver works great for the version aspects of the POM file.  I am having the <scm><tag> also conflict in the pom file.  Does anyone have a work-around for this?

**Comment by agusmba** [comment]
This driver addresses conflicts in the version part of the POM by following set rules.
Any other conflict should be reviewed by hand, as there are endless possibilities for additional conflicts in other parts of the POM.

That said, if you have a *very specific* conflict that happens *very often* to you, then it might make sense for you to extend the driver to solve it for you

**Comment by ralfth** [comment]
While this is all true, versions are also changed when releasing the project using the Maven release plugin which causes changes in the scm/tag tag.

My understanding is that usually the value of scm/tag is HEAD except between the 'prepare' and 'perform' step of the Maven release plugin since Maven stores the git tag of the release being made in this element so that the 'perform' step can checkout the tag and finish the release. Also, during the 'perform' step, the value of scm/tag is set back to HEAD.
I don't use the maven release plugin myself so this can be wrong.

So a conflict can only happen when you merge a Git tag which means changing value HEAD of scm/tag to something else.

There is a quite common scenario which may cause conflicts or wrong values in scm/tag:
Merging a tag to a branch that is in development and keep the current version
Because before merging the value of scm/tag is HEAD, however, after merging it'll be changed to the tag name even though the project version was kept. So now there is a wrong value in scm/tag since it should still be HEAD.
If the git tag name is now kept in scm/tag, a subsequent merge of another tag may cause conflicts.

So I think changing scm/tag value along with the version would not only prevent wrong values but also conflicts.
